version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "andrewFootballStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kni8z5nxcykx"
s3_prefix = "andrewFootballStack"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
